# fly.toml app configuration file generated for stigmerge-seed-demofile on 2025-07-08T22:49:42-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'stigmerge-seed-demofile'
primary_region = 'ord'

[build]
  dockerfile = 'examples/fly.io/Dockerfile'

[[mounts]]
  source = 'stigmerge_seed_demofile_data'
  destination = '/state'
  initial_size = '1GB'

[[services]]
  protocol = 'udp'
  internal_port = 5150

  [[services.ports]]
    port = 5150

[[services]]
  protocol = 'tcp'
  internal_port = 5150

  [[services.ports]]
    port = 5150

[[vm]]
  size = 'shared-cpu-1x'
